clients:
  generate_semantic_map_owl:
    service: "/knowrob_semantic_map_to_owl/generate_owl_map"
  prolog_query:
    service: "/json_prolog/simple_query"
  prolog_next_solution:
    service: "/json_prolog/next_solution"
  prolog_finish:
    service: "/json_prolog/finish"
publishers:
  marker_array:
    topic: "~markers"
    queue_size: 1
    latch: true

map:
  frame_id: "map"
  stamp: 2015-03-12T15:08:00
  
  namespace: "http://asl.ethz.ch/example/semantic_map.owl"
  prefixes:
    - name: "map"
      prefix: "http://asl.ethz.ch/example/semantic_map.owl#"
  imports:
    - "package://knowrob_common/owl/knowrob.owl"
    
  address:
    room_nr: 224
    floor_nr: "J"
    street_nr: 21
    street_name: "Leonhardstrasse"
    city_name: "Zurich"
  
  object_properties:
    hinged_to:
      id: "knowrob:hingedTo"
  
  data_properties:
    purchase_price:
      id: "knowrob:purchasePrice"
  
  objects:
    - id: "Cupboard1"
      type: "Cupboard"
      size:
        x: 0.5
        y: 0.6
        z: 0.7
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        w: 1
        x: 0
        y: 0
        z: 0
      purchase_price: 400
    - id: "Door1"
      type: "Door"
      size:
        x: 0.01
        y: 0.6
        z: 0.7
      position:
        x: 0.26
        y: 0
        z: 0
      orientation:
        w: 1
        x: 0
        y: 0
        z: 0
      part_of: "Cupboard1"
      hinged_to: "Cupboard1"
    - id: "HingedJoint1"
      type: "HingedJoint"
      size:
        x: 0.01
        y: 0.007
        z: 0.006
      position:
        x: 0.255
        y: -0.3
        z: -0.003
      orientation:
        w: 1
        x: 0
        y: 0
        z: 0
      part_of: "Door1"
    - id: "Handle1"
      type: "Handle"
      size:
        x: 0.05
        y: 0.06
        z: 0.07
      position:
        x: 0.26
        y: 0
        z: 0
      orientation:
        w: 1
        x: 0
        y: 0
        z: 0
      part_of: "Door1"

visualization:
  labels:
    scale: 0.2
    color:
      r: 1.0
      g: 1.0
      b: 1.0
      a: 1.0
  bounding_boxes:
    color:
      r: 1.0
      g: 1.0
      b: 1.0
      a: 0.2
  meshes:
    embedded_materials: true
    color:
      r: 0.6
      g: 0.6
      b: 0.6
      a: 1.0
